import java.util.*;

public class Main {
    public static void main(String[]args){
        Scanner myObj = new Scanner(System.in);
        System.out.println("Hello Player, Do you want to play a game? (y/n)");
        String yesOrNo = myObj.nextLine();
        //System.out.println("Your answer was " +yesOrNo);


        System.out.println("Choose an option between rock, paper or scissors");
        String playerOne = myObj.nextLine();
        System.out.println("You chose "+playerOne);


        String game [] = {"rock", "paper", "scissors"};
        Random random = new Random();//created a random object which generates random objects
        int index = random.nextInt(game.length);//generates a random int "index" btwn 0 and 2, the length of the "game"
        String computer = game[index];//sets the "computer" to the element of the "game" array at index generated by "random"
        System.out.println("Computer chose "+computer);

        //if statements to determine the winner
        if (playerOne.contentEquals(computer)) {
            System.out.println("Draw!!");
        } else if (playerOne.equals("rock") && computer.equals("scissors")) {
            System.out.println("You Won");
        }else if (playerOne.equals("rock") && computer.equals("paper")) {
            System.out.println("Computer Won");
        }

        else if (playerOne.equals("paper") && computer.equals("rock")) {
            System.out.println("You Won");
        } else if (playerOne.equals("paper") && computer.equals("scissors")) {
            System.out.println("Computer Won");
        }


        else if (playerOne.equals("scissors") && computer.equals("paper")) {
            System.out.println("You Won");
        } else if (playerOne.equals("scissors") && computer.equals("rock")) {
            System.out.println("Computer Won");
        } else{
            System.out.println("Invalid Options");
        }

    }
}
